### ISSUE TITLE
PhantomJS 2.0?

### ISSUE THREAD

**Issue by pamelafox** [mrhooray/gulp-mocha-phantomjs#24] opened 2014-12-29 19:02 UTC
I notice that some issues I'm experiencing in our unit tests (like https://github.com/ariya/phantomjs/issues/11872) are fixed in Phantom 2.0. I'll admit I'm not deeply familiar with PhantomJS and whether 2.0 is a major backwards breaking version, I'm wondering if you can tell me if there are any plans to have gulp-mocha-phantomjs bring in 2.0?

Thanks!

**Comment by johanpoirier** [comment] 2015-02-03 10:41
PhantomJS 2.0 has landed. Will you update the plugin @mrhooray ?

**Comment by mrhooray** [comment] 2015-02-05 09:49
little busy these days but i'll get on this asap

**Comment by mrhooray** [comment] 2015-02-07 06:51
npm wrapper for phantomjs hasn't hit 2.0 yet
https://www.npmjs.com/package/phantomjs

**Comment by johanpoirier** [comment] 2015-02-09 08:56
We'll be waiting ;-)

**Comment by mrhooray** [comment] 2015-04-06 15:52
hmm phantomjs 2.0 removes support of coffee script which is used by mocha-phantomjs

there is consideration of rewrite/transform core part into javascript https://github.com/metaskills/mocha-phantomjs/issues/175

**Comment by nathanboktae** [comment] 2015-07-17 16:26
Since #35 and `0.8.0` , `gulp-mocha-phantomjs` is using `mocha-phantomjs-core` so it controls the `phantomjs` dependency fully - however 2.0 never got linux binaries so the npm package wrapper around phantomjs still doesn't have a 2.0 release. So after it's resolved (Medium/phantomjs#288) then this plugin can move forward.

**Comment by lpsBetty** [comment] 2016-01-27 09:50
hmm I got this:
```
node_modules/mocha-phantomjs-core/phantomjs --version
2.0.0
```
that's why I thought MutationObserver API would work in my test - but it isn't :( 
How can I make sure gulp-mocha-phantomjs uses 2.0.0?

**Comment by mrhooray** [comment] 2016-01-27 18:57
@lpsBetty Medium/phantomjs#288 just closed, i'll have a look to upgrade to phantomjs 2.0

**Comment by laurelnaiad** [comment] 2016-01-31 22:06
I made [a branch](https://github.com/laurelnaiad/gulp-mocha-phantomjs/tree/v0.10.2) that sets phantomjs-prebuilt^2.1.3 as a peerDependency. Solved my angular 1.5 problems (akin to https://github.com/angular/angular.js/issues/13794).

**Comment by mrhooray** [comment] 2016-02-01 04:12
@lpsBetty @laurelnaiad released v0.11.0 with phantomjs 2 and updated deps
will release v1.0.0 some time later if no critical issues

**Closed by mrhooray** 2016-02-01 04:12 UTC

**Comment by nathanboktae** [comment] 2016-02-01 05:32
> if no critical issues.

A PR for using phantomjs-prebuilt and [nearly half the tests failed](https://travis-ci.org/nathanboktae/mocha-phantomjs/builds/105362952). Moreover I haven't done added 2.1 as a test target yet on `mocha-phantomjs-core`. 

It's highly likely you broke a lot of people.

**Comment by mrhooray** [comment] 2016-02-01 06:29
@nathanboktae this module is pre 1.0 and any minor version bump may have breaking changes

**Comment by lpsBetty** [comment] 2016-02-01 08:30
hmm I tried it, but I got `DOMExpectionError` on some tests that were working before!  do you need more details?

**Comment by laurelnaiad** [comment] 2016-02-01 09:18
hmmm.. I didn't mean to instigate any sudden moves in this library.... I was just throwing that branch out for people to use while the dust is settling, if it helps them. I guess by putting the dependency as a peer,  I was also sort of hinting that hardcoding any version (be it 1.x or 2.x) makes it harder for us in the peanut gallery to ensure we have the version we're trying to use.  In any case, I hope you didn't think I was gunning for an instant change in master or putting pressure on the subject. :)

**Comment by mrhooray** [comment] 2016-02-01 09:48
@laurelnaiad depends on perspective, peer dependency sometimes does more harm than what it brings and npm v3 stops installing peer dependencies of packages

v0.11.0 was built after following comment in nathanboktae/mocha-phantomjs#175
```
You have been able to use phantomjs 2.0 with mocha-phantomjs-core for months now
```
the update passes tests as glue between `gulp`, `mocha-phantomjs-core` & `phantomjs` but apparently there are more complicated problems as mentioned in nathanboktae/mocha-phantomjs#224
updates of these three will be reflected in newer versions of this plugin

v0.10.x would always be available to use. people shouldn't be affected unless `*` or `^` is used for pre v1 package, which are anti patterns and should be avoided

**Comment by nathanboktae** [comment] 2016-02-06 04:29
FYI I added 2.1.1 as a target to `mocha-phantomjs-core` and [all tests passed](https://travis-ci.org/nathanboktae/mocha-phantomjs-core/jobs/107391351) that targeted 2.0 (still a few outstanding 2.0 issues.

So it could be test setup differences between `mocha-phantomjs` and `mocha-phantomjs-core` or some packaging issues with `phantomjs-prebuilt`, but not any functionality regressions of phantomjs 2.0 -> 2.1.
