### ISSUE TITLE
Error in plugin 'gulp-mocha-phantomjs'

### ISSUE THREAD

**Issue by trizko** [mrhooray/gulp-mocha-phantomjs#41] opened 2015-08-07 17:38 UTC
Output:
```
[10:21:35] Finished 'phantomjs' after 5.9 ms
Failed to run any tests.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error in plugin 'gulp-mocha-phantomjs'
test failed
```

Environment:
```
...
    "gulp": "^3.9.0",
    "gulp-mocha-phantomjs": "^0.8.1",
...
    "engine": "node 0.10.38"
...
```

gulpfile.js
```javascript
var gulp = require('gulp');
var mochaPhantomJS = require('gulp-mocha-phantomjs');

gulp.task('phantomjs', function () {
    return gulp
    .src('./tests/unit.html')
    .pipe(mochaPhantomJS({'reporter' : 'spec'}));
});
```

This works in version `0.7.0`

**Comment by mrhooray** [comment] 2015-08-21 06:48
could you share what's the content of unit.html or publish a repo for reproducing this problem so i can investigate?

**Comment by atticae** [comment] 2015-08-21 17:09
I had the same problem and after some digging I realized that it happened because an absolute path was passed to phantomjs, but without the "file:///" prefix.

When I use this gulpfile:
```javascript
var mochaPhantomJS = require('gulp-mocha-phantomjs');
[...]
gulp.task('mochaPhantom', function() {
    return gulp.src('wwwroot/MochaTestRunner2.html')
               .pipe(mochaPhantomJS());
});
```

the gulp tasks ends up passing this to phantomjs
> c:/work/MyProject/wwwroot/MochaTestRunner2.html
which fails. It seems to need this instead:
> file:///c:/work/MyProject/wwwroot/MochaTestRunner2.html

I am really new to the whole node and gulp topic, but I found that changing the line 23 in index.js to the following made my gulp task work:

```javascript
'file:///' + mergeQuery(file.path, options.mocha),
```

That's probably a bad hack, but maybe it can help you identify the problem?

I am using gulp-mocha-phantomjs version 0.9.0 and node version 0.12.6 on Windows 7.

**Comment by mrhooray** [comment] 2015-08-23 18:31
besides local file, this plugin also supports served pages like
```js
gulp.task('test', function () {
    var stream = mochaPhantomJS();
    stream.write({path: 'http://localhost:8000/index.html'});
    stream.end();
    return stream;
});
```
so simply adding 'file://' prefix may break above example

running following example on unix environment resolves to path `/Users/rui/github/mrhooray/gulp-mocha-phantomjs/test/fixture-pass.html` which can be successfully read by phantomjs
```js
gulp.task('run', function () {
    return gulp
    .src('test/fixture-pass.html')
    .pipe(mochaPhantomJS({reporter: 'spec'}));
});
```
could you try adding '/' instead of 'file:///'? If this, it might just be gulp.src returns incorrect absolute path on windows platform

**Comment by atticae** [comment] 2015-08-25 13:42
Prefixing with '/' seems to work as well. But wouldn't it be best to build a complete URI, including the scheme name ('http' or 'file')? Sounds more robust to me than relying on phantomjs to figure it out anyway. (Honestly asking, as I said I know little about the whole topic.)

**Comment by mrhooray** [comment] 2015-08-26 02:58
how would you know which schema to use for a URI without schema?
also force adding '/' would not work for URIs with schema

this plugin doesn't intend to change the path/URI except mocha options as querystring
it's either phantomjs cannot take file path like yours or gulp.src doesn't return correct path on windows

**Comment by atticae** [comment] 2015-08-26 11:14
I figure it's not gulp.src's fault, as this only seems to pass a stream with the relative path (in my case ```wwwroot\MochaTestRunner2.html```) to gulp-mocha-phantomjs.

Then somewhere within the index.js the relative path gets transformed to an absolute windows path (```c:/work/MyProject/wwwroot/MochaTestRunner2.html```), which phantomjs can't handle on windows without the ```file://``` prefix.

You say "this plugin doesn't intend to change the path/URI except mocha options as querystring", but apparently it does (by making it absolute instead of keeping it relative). Would it be an option to not transform the input into an absolute path? I think phantomjs could handle the relative path alot better on windows.

**Comment by atticae** [comment] 2015-08-26 11:44
I see where you are coming from, but from my understanding gulp.src doesn't care about URIs, but phantomjs expects a URI to work correctly in every case. So both work as intended, but they need some intermediate handling to work together. I don't see why this module shouldn't make sure that whatever you pass to phantomjs is a valid URI?

> how would you know which scheme to use for a URI without scheme?

My understanding is that if you don't get a valid URI with a scheme identifier, it's usually implied that it's a file system path. That's why we prepend all our URLs with 'http://', right? Because otherwise it's assumed to be a local file.

**Comment by mrhooray** [comment] 2015-08-28 03:04
if gulp.src is giving a valid path, then it's phantomjs cannot handle a valid path.
if phantomjs can handle all valid paths, then it's gulp.src giving a incorrect one.
you should reach to whichever doing the incorrect thing

how do you know http and file are the only two scheme?

**Comment by mrhooray** [comment] 2015-08-28 03:05
no update from @trizko , closing this issue

**Closed by mrhooray** 2015-08-28 03:05 UTC

**Comment by atticae** [comment] 2015-08-28 18:17
> how do you know http and file are the only two schemes?

They are not. That does not change the fact that if no scheme is given, it's usually implied that it the scheme is file://

> if gulp.src is giving a valid path, then it's phantomjs cannot handle a valid path.
> if phantomjs can handle all valid paths, then it's gulp.src giving a invalid one.

Here is the problem. gulp.src is giving a valid ***path***, but phantomjs is expecting a valid ***URI***. They both work correct, and if we want to take output from gulp.src and feed it into phantomjs, we may have to do some conversion work. That's my understanding of the issue, anyway.

I totally understand your point, but you are mixing the two concepts (path and URI). If your stance is that gulp-mocha-phantomjs just takes whatever it is given and forwards it to phantomjs, then we would need an additional converter in the pipeline to create proper URIs from the output of gulp.src.

Then you should at least warn Windows users that your standard example (just piping from gulp.src) may not work for them.

**Comment by mrhooray** [comment] 2015-08-28 18:42
> gulp.src is giving a valid path, but phantomjs is expecting a valid URI

this is true, the reason i mixed using path and URI is that browers/phantomjs on unix would automatically convert a path into file scheme URI
i don't have a windows environment for testing this, but i think your point is correct, it makes sense to provide URI for phantomjs script
> it's usually implied that it the scheme is file://

i am not sure about whether this assumption is safe or not, but given browsers/phantomjs does that, i have no objection of doing the same

thanks for your patience on clarifying the issue and sorry that i didn't realize the exact issue sooner
i'll make an update this weekend

also based on your problem, it seems phantomjs on windows cannot covert a path to URI but it is separate issue

**Comment by atticae** [comment] 2015-08-28 23:28
Cool, thanks for taking the time to look at this issue! Your module is a big help, keep up the great work.
